[package]
name = "minesweeper"
version = "0.1.0"
authors = ["Macha <charlotte.calisto@free.fr>"]
edition = "2018"

[dependencies]
rand = "0.7"
ansi_term = "0.12"
ggez = "0.7"
cgmath = {version= "0.17", features=["mint"]}
